### ISSUE TITLE
Unable to automatically inject tree repository

### ISSUE THREAD

**Issue by hotsezus** [nestjs/typeorm#1367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i'm injecting repository for entity which has `@Tree(...)` decorator on it
```typescript
@Tree('materialized-path', {
  closureTableName: 'user_groups_closure',
  ancestorColumnName: (column) => 'ancestor_' + column.propertyName,
  descendantColumnName: (column) => 'descendant_' + column.propertyName,
})
@Entity('user_groups')
export class UserGroup {
  ...
}
```
i'm getting `Repository` instance instead of `TreeRepository` in my service

```typescript
@Injectable()
export class UserGroupService {
  constructor(
    @InjectRepository(UserGroup)
    private readonly userGroupsRepo: TreeRepository<UserGroup>,
  ) {}

  async tree(): Promise<UserGroup[]> {
    // this.userGroupsRepo.constructor.name is 'Repository'
    return this.userGroupsRepo.findTrees();
  }
```

to fix this i have to inject entity manager and access tree repository through it

```typescript
@Injectable()
export class UserGroupService {
  constructor(
    @InjectEntityManager()
    private entityManager: EntityManager,
  ) {}

  async tree(): Promise<UserGroup[]> {
    const treeRepo = this.entityManager.getTreeRepository(UserGroup);
    // treeRepo.constructor.name is 'TreeRepository'
    return this.userGroupsRepo.findTrees();
  }
```

### Minimum reproduction code

https://codesandbox.io/s/wonderful-shirley-tqbefi?file=/src/groups/group.service.ts

### Steps to reproduce

1. Prepare postgres database with default connection options
2. Install dependencies and step into `repl`
```bash
npm i
npm run repl
```
3. Access `GroupService->resolveTreeUsingInjectedRepo()` and `GroupService->resolveTreeUsingEntityManagerRepo()` to see how each of them work

### Expected behavior

Repository of tree entity injected using `@InjectRepository()` decorator should be a `TreeRepository` instance

### Package version

^9.0.0

### NestJS version

^9.0.8

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hotsezus** [comment]
Also, nice to mention that it stopped working when my project transferred from `NestJS` 8.* to 9.* and `TypeORM` 0.2.* to 0.3.*

**Comment by micalevisk** [comment]
this should be fixed by #1333

**Comment by kamilmysliwiec** [comment]
Fixed in 9.0.1

**Comment by Moinketroa** [comment]
I'm still experiencing this issue in 9.0.1
Is using `@InjectRepository` and `TreeRepository<>` the only thing to do ?
