### ISSUE TITLE
NestJS import "forRootAsync" only first one

### ISSUE THREAD

**Issue by vgladimir** [nestjs/typeorm#48]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
```
@Module({
  providers: [
    DatabaseService,
  ],
  exports: [
    DatabaseService,
  ],
  imports: [
    TypeOrmModule.forRootAsync({
      useFactory: async (config: ConfigService) => {
        const options = config.get('database.databases.email');

        options.name = 'default';
        options.entities = [__dirname + '/../app/entities/*.entity{.ts,.js}'];

        return options;
      },
      inject: [ConfigService],
    }),
    TypeOrmModule.forRootAsync({
      useFactory: async (config: ConfigService) => {
        console.log('I AM IGNORED');

        const options = config.get('database.databases.app');

        options.name = 'app';
        options.entities = [__dirname + '/../app/entities/*.entity{.ts,.js}'];

        return options;
      },
      inject: [ConfigService],
    }),
  ],
})
```

## Expected behavior
Nest only load's first import. The second one is ignored. The module should load all async modules.

BTW. Maybe it would be better if module can accept array of connection options?

## Environment

<pre><code>
Nest version: 5.3.7

 
For Tooling issues:
- Node version: v9.4.0
- Platform: Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Thanks for reporting. Fixed in 5.2.2!

**Comment by maroon1** [comment]
still not working! can't inject relative entity to feature module

```typescript
@Module({
  imports: [
    TypeOrmModule.forFeature([SystemSettingEntity], 'gameServerMainConnection'),
  ],
  controllers: [SystemSettingController],
  providers: [SystemSettingService],
})
export class SystemSettingModule {}
```

```
[Nest] 26092   - 2018-9-20 17:12:28   [ExceptionHandler] Nest can't resolve dependencies of the SystemSettingEntityRepository (?). Please make sure that the argument at index [0] is available in the current context. +5ms
Error: Nest can't resolve dependencies of the SystemSettingEntityRepository (?). Please make sure that the argument at index [0] is available in the current context.
    at Injector.lookupComponentInExports (D:\Projects\game-platform\game-management\game-management-server\node_modules\@nestjs\core\injector\injector.js:146:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
 1: node::DecodeWrite
 2: node::DecodeWrite
 3: v8::internal::interpreter::BytecodeDecoder::Decode
 4: v8::internal::RegExpImpl::Exec
 5: v8::internal::RegExpImpl::Exec
 6: v8::internal::RegExpImpl::Exec
 7: 0000000277904281
```

**Comment by kamilmysliwiec** [comment]
See that `name`:
https://github.com/nestjs/typeorm/blob/master/lib/interfaces/typeorm-options.interface.ts
should be passed at the same level as `useFactory` in case of the multiple connections.
```typescript
 TypeOrmModule.forRootAsync({
      name: 'gameServerMainConnection',
      useFactory: (config: ConfigService) => ({
        ...
        type: 'mysql',
        host: '127.0.0.1',
     }),
})
```

**Comment by Diluka** [comment]
Maybe `name` property shall be exclude from `TypeOrmModuleOptions` returned by `useFactory`

**Comment by chriscarpenter12** [comment]
This threw me off too. I was trying to pass the `name` key with the result of the `useFactory` as I was pulling all the variables from my `ConfigService`.

**Comment by vgladimir** [comment]
@Diluka @chriscarpenter12 Sorry, but was it the problem? Me is also passing connection `name` from config. All is working fine.

**Comment by Diluka** [comment]
I don't use `name` or `ormconfig` anymore. I use `ConfigService` to provide all the options.

**Comment by chriscarpenter12** [comment]
@vgladimir Can you show us how you are using `ConfigService` for the name key?

I could be wrong, but I couldn't get it to work with `ConfigService` either as name is outside the injection of `ConfigService` in the `useFactory`.

```
TypeOrmModule.forRootAsync({
  name: ConfigService.get('some.key.here'), // <-- Config is inaccessible here
  useFactory: (config: ConfigService) => config.typeorm[2] as any,
  inject: [ConfigService],
}),
```

Hence we were trying to erroneously pass name with the config in `useFactory`.
```
TypeOrmModule.forRootAsync({
  useFactory: (config: ConfigService) => ({
    name: config.get('some.key.here'),
    ...other keys
  }),
  inject: [ConfigService],
}),
```

The [name](https://github.com/nestjs/typeorm/blob/master/lib/interfaces/typeorm-options.interface.ts#L19) is a string and we can't return a promise from the ConfigService here.

**Comment by vgladimir** [comment]
@chriscarpenter12 The second example is right. But I don't understand why you return Promise from `ConfigService`. In the `get` method you can return `string` and I think it is better. Btw, It is your decision and I don't know your project specification. If you have a Promises then you can use `async` function.

```ts
TypeOrmModule.forRootAsync({
  useFactory: async (config: ConfigService) => ({
    name: await config.get('some.key.here'),
    ...other keys
  }),
  inject: [ConfigService],
}),
```

**Comment by chriscarpenter12** [comment]
@vgladimir I don't disagree about the use of async/await, but my point was that if you try to use the `name` key in the `useFactory` response it doesn't work. As @kamilmysliwiec said it needed to be outside of `useFactory`.

**Comment by ddehghan** [comment]
I have minim repro of the name issue outside of the useFactory. it causes and error if I have t ORM connections. 
https://github.com/nestjs/typeorm/issues/156 .

**Comment by acepace** [comment]
The documentation seems to be wrong as the result of `useFactory` is ignored if there is a config named default.

**Comment by Rainson12** [comment]
this is also the case when you do useClass => (....)... the name property which you would return in the useClass is omitted. Instead the name property must be defined next to the useClass Property.
